import { getChatGPTUser } from '../../chatgpt-auth';
import { database } from '../../../lib/data';
async function owner(){return (await getChatGPTUser())?.userId;}
export async function GET(){const user=await owner();if(!user)return Response.json({error:'Sign in to load your collection.'},{status:401});try{return Response.json({items:(await database().prepare('SELECT * FROM collection WHERE owner=? ORDER BY rowid DESC').bind(user).all()).results.map((r:any)=>({...r,metadata:JSON.parse(r.metadata)}))});}catch{return Response.json({error:'Your collection could not be loaded. Please retry.'},{status:503})}}
export async function POST(req:Request){const user=await owner();if(!user)return Response.json({error:'Sign in to save your collection.'},{status:401});
 try{const p:any=await req.json();if(!['en','ja'].includes(p.lang)||typeof p.card!=='string'||p.card.length>100||typeof p.variant!=='string'||p.variant.length>60||!['Near Mint','Lightly Played','Moderately Played','Heavily Played','Damaged'].includes(p.condition)||!Number.isInteger(p.quantity)||p.quantity<1||p.quantity>10000||!Number.isFinite(p.cost)||p.cost<0||p.cost>1e8||!p.metadata||JSON.stringify(p.metadata).length>4000)return Response.json({error:'Check quantity, cost, and card details.'},{status:400});
 const id=p.id||crypto.randomUUID();if(typeof id!=='string'||id.length>100)return Response.json({error:'Invalid entry.'},{status:400});
 if(p.id){const result=await database().prepare('UPDATE collection SET quantity=?,cost=?,condition=?,variant=? WHERE id=? AND owner=?').bind(p.quantity,p.cost,p.condition,p.variant,id,user).run();if(!result.meta.changes)return Response.json({error:'Entry not found.'},{status:404});}
 else await database().prepare('INSERT INTO collection(id,owner,card,lang,variant,condition,quantity,cost,metadata) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,user,p.card,p.lang,p.variant,p.condition,p.quantity,p.cost,JSON.stringify(p.metadata)).run();
 return Response.json({ok:true});}catch{return Response.json({error:'Your changes could not be saved. Please retry.'},{status:503})}}
export async function DELETE(req:Request){const user=await owner();if(!user)return Response.json({error:'Sign in to edit your collection.'},{status:401});try{const id=new URL(req.url).searchParams.get('id');await database().prepare('DELETE FROM collection WHERE id=? AND owner=?').bind(id,user).run();return Response.json({ok:true});}catch{return Response.json({error:'Entry could not be removed.'},{status:503})}}
